base_images:
  base:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
binary_build_commands: make -f Makefile.prow install && make -f Makefile.prow build
build_root:
  image_stream_tag:
    name: builder
    namespace: open-cluster-management
    tag: nodejs14-linux-amd64
images:
- dockerfile_path: Dockerfile.prow
  to: console
promotion:
  name: cahl-copyright
  namespace: open-cluster-management
resources:
  '*':
    limits:
      memory: 10Gi
    requests:
      cpu: 200m
      memory: 4Gi
tests:
- as: lint
  commands: make -f Makefile.prow lint
  container:
    from: bin
- as: check
  commands: make -f Makefile.prow check
  container:
    from: bin
- as: unit
  commands: make -f Makefile.prow unit-tests
  container:
    from: bin
zz_generated_metadata:
  branch: cahl-copyright
  org: open-cluster-management
  repo: console
