base_images:
  base:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: builder
    namespace: open-cluster-management
    tag: nodejs14-linux-amd64
images:
- dockerfile_path: Dockerfile.prow
  to: console
promotion:
  name: latest
  namespace: open-cluster-management
resources:
  '*':
    limits:
      memory: 10Gi
    requests:
      cpu: 200m
      memory: 4Gi
tests:
- as: unit
  commands: |
    cd /app/frontend
    npm run lint
    npm run check
    npm run test
    cd /app/backend
    npm run lint
    npm run check
    npm run test
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: open-cluster-management
  repo: console
