base_images:
  base:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: builder
    namespace: open-cluster-management
    tag: nodejs14-linux-amd64
images:
- dockerfile_path: Dockerfile.prow
  to: console
promotion:
  name: "2.3"
  namespace: open-cluster-management
resources:
  '*':
    limits:
      memory: 10Gi
    requests:
      cpu: 200m
      memory: 4Gi
tests:
- as: unit
  commands: |
    /app/frontend
    RUN npm run lint
    RUN npm run check
    RUN npm run test
    /app/backend
    RUN npm run lint
    RUN npm run check
    RUN npm run test
  container:
    from: src
zz_generated_metadata:
  branch: release-2.3
  org: open-cluster-management
  repo: console
