base_images:
  base:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
binary_build_commands: make -f Makefile.prow install && make -f Makefile.prow build
build_root:
  image_stream_tag:
    name: builder
    namespace: open-cluster-management
    tag: nodejs14-linux-amd64
images:
- dockerfile_path: Dockerfile.prow
  to: console
promotion:
  disabled: true
  name: "2.3"
  namespace: open-cluster-management
resources:
  '*':
    limits:
      memory: 10Gi
    requests:
      cpu: 200m
      memory: 4Gi
tests:
- as: lint
  commands: |
    export SELF="make -f Makefile.prow"
    make -f Makefile.prow lint
  container:
    from: bin
- as: check
  commands: |
    export SELF="make -f Makefile.prow"
    make -f Makefile.prow check
  container:
    from: bin
- as: unit-tests
  commands: |
    export SELF="make -f Makefile.prow"
    make -f Makefile.prow unit-tests
  container:
    from: bin
- as: sonar
  commands: |
    mkdir /tmp/npmcache
    export npm_config_cache=/tmp/npmcache
    export SELF="make -f Makefile.prow"
    make -f Makefile.prow sonar/js/jest-init
    make -f Makefile.prow unit-tests
    make -f Makefile.prow sonar/js/prow
  container:
    from: bin
  secrets:
  - mount_path: /etc/sonarcloud/
    name: acm-sonarcloud-token
zz_generated_metadata:
  branch: release-2.3
  org: open-cluster-management
  repo: console
