base_images:
  base:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: builder
    namespace: open-cluster-management
    tag: go1.15-linux-amd64
images:
- dockerfile_path: Dockerfile.prow
  from: base
  to: console
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.7"
  namespace: ocp
zz_generated_metadata:
  branch: main
  org: open-cluster-management
  repo: console
