base_images:
  base:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: builder
    namespace: open-cluster-management
    tag: nodejs14-linux-amd64
images:
- dockerfile_path: Dockerfile.prow
  to: console
promotion:
  name: latest
  namespace: open-cluster-management
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: 100m
      memory: 2Gi
tag_specification:
  name: "4.7"
  namespace: ocp
zz_generated_metadata:
  branch: main
  org: open-cluster-management
  repo: console
